/* Generated by scripts/build_typeface.py -- do not edit.
 * Rebuild after changing art/ballysanser-sheet.png.
 *
 * A plain global rather than a module export: the page loads
 * its scripts the old way, as graph.js and regions.js do. */
const BALLYSANSER = {
  "sheet": "img/ballysanser.png",
  "sheetWidth": 6716,
  "band": 352,
  "tracking": 0.07,
  "wordSpace": 0.25,
  "glyphs": {
    "a": {
      "x": 24,
      "w": 214
    },
    "b": {
      "x": 262,
      "w": 215
    },
    "c": {
      "x": 501,
      "w": 207
    },
    "d": {
      "x": 732,
      "w": 206
    },
    "e": {
      "x": 962,
      "w": 176
    },
    "f": {
      "x": 1162,
      "w": 175
    },
    "g": {
      "x": 1361,
      "w": 219
    },
    "h": {
      "x": 1604,
      "w": 240
    },
    "i": {
      "x": 1868,
      "w": 47
    },
    "j": {
      "x": 1939,
      "w": 192
    },
    "k": {
      "x": 2155,
      "w": 215
    },
    "l": {
      "x": 2394,
      "w": 174
    },
    "m": {
      "x": 2592,
      "w": 265
    },
    "n": {
      "x": 2881,
      "w": 229
    },
    "o": {
      "x": 3134,
      "w": 218
    },
    "p": {
      "x": 3376,
      "w": 212
    },
    "q": {
      "x": 3612,
      "w": 260
    },
    "r": {
      "x": 3896,
      "w": 244
    },
    "s": {
      "x": 4164,
      "w": 286
    },
    "t": {
      "x": 4474,
      "w": 196
    },
    "u": {
      "x": 4694,
      "w": 232
    },
    "v": {
      "x": 4950,
      "w": 285
    },
    "w": {
      "x": 5259,
      "w": 269
    },
    "x": {
      "x": 5552,
      "w": 244
    },
    "y": {
      "x": 5820,
      "w": 272
    },
    "z": {
      "x": 6116,
      "w": 264
    },
    "'": {
      "x": 6404,
      "w": 47
    },
    "?": {
      "x": 6475,
      "w": 217
    }
  }
};
