/* Generated by scripts/build_typeface.py -- do not edit.
 * Rebuild after changing art/ballysanser-sheet.png.
 *
 * A plain global rather than a module export: the page loads
 * its scripts the old way, as graph.js and regions.js do. */
const BALLYSANSER = {
  "sheet": "img/ballysanser.png",
  "sheetWidth": 6020,
  "band": 352,
  "tracking": 0.07,
  "wordSpace": 0.25,
  "glyphs": {
    "a": {
      "x": 0,
      "w": 214
    },
    "b": {
      "x": 214,
      "w": 215
    },
    "c": {
      "x": 429,
      "w": 207
    },
    "d": {
      "x": 636,
      "w": 206
    },
    "e": {
      "x": 842,
      "w": 176
    },
    "f": {
      "x": 1018,
      "w": 175
    },
    "g": {
      "x": 1193,
      "w": 219
    },
    "h": {
      "x": 1412,
      "w": 240
    },
    "i": {
      "x": 1652,
      "w": 47
    },
    "j": {
      "x": 1699,
      "w": 192
    },
    "k": {
      "x": 1891,
      "w": 215
    },
    "l": {
      "x": 2106,
      "w": 174
    },
    "m": {
      "x": 2280,
      "w": 265
    },
    "n": {
      "x": 2545,
      "w": 229
    },
    "o": {
      "x": 2774,
      "w": 218
    },
    "p": {
      "x": 2992,
      "w": 212
    },
    "q": {
      "x": 3204,
      "w": 260
    },
    "r": {
      "x": 3464,
      "w": 244
    },
    "s": {
      "x": 3708,
      "w": 286
    },
    "t": {
      "x": 3994,
      "w": 196
    },
    "u": {
      "x": 4190,
      "w": 232
    },
    "v": {
      "x": 4422,
      "w": 285
    },
    "w": {
      "x": 4707,
      "w": 269
    },
    "x": {
      "x": 4976,
      "w": 244
    },
    "y": {
      "x": 5220,
      "w": 272
    },
    "z": {
      "x": 5492,
      "w": 264
    },
    "'": {
      "x": 5756,
      "w": 47
    },
    "?": {
      "x": 5803,
      "w": 217
    }
  }
};
