/* Generated by scripts/build_gable.py -- do not edit.
 * Rebuild after changing art/ballymander-article.png. */
const GABLE = {
  "image": "img/ballymander-article.png",
  "width": 3228,
  "height": 978,
  "front": 1619,
  "title": {
    "x": 0.520756,
    "y": 0.436605,
    "w": 0.442069,
    "h": 0.517382
  }
};
